src/main/java/com/devcourse/ReviewRanger/question/domain/Question.java
src/main/java/com/devcourse/ReviewRanger/question/domain/QuestionOption.java
src/main/java/com/devcourse/ReviewRanger/question/domain/QuestionType.java
src/main/java/com/devcourse/ReviewRanger/survey/domain/Survey.java
src/main/java/com/devcourse/ReviewRanger/survey/domain/SurveyType.java
src/main/java/com/devcourse/ReviewRanger/surveyresult/domain/DeadlineStatus.java
src/main/java/com/devcourse/ReviewRanger/surveyresult/domain/SurveyResult.java

- 설문, 질문, 질문 유형, 설문 결과에 대한 엔티티를 추가했습니다.
- 논의한대로 모든 연관관계를 끊고, 외래키를 통해 연관될 수 있도록 했습니다.
- 유효성 검사를 세세하게 하지 않았습니다. 논의되지 않은 상황에서 혼자 결정하는 것이 불필요했고 서비스 로직을 테스트해봐야 구체적으로 나올 것 같았습니다.

[REV-39] 설문, 질문 관련 엔티티 생성 

---

src/main/java/com/devcourse/ReviewRanger/question/application/QuestionService.java
src/main/java/com/devcourse/ReviewRanger/question/domain/Question.java
src/main/java/com/devcourse/ReviewRanger/question/domain/QuestionOption.java
src/main/java/com/devcourse/ReviewRanger/question/repository/QuestionOptionRepository.java
src/main/java/com/devcourse/ReviewRanger/question/repository/QuestionRepository.java
src/main/java/com/devcourse/ReviewRanger/survey/domain/Survey.java
src/main/java/com/devcourse/ReviewRanger/surveyresult/domain/SurveyResult.java
src/test/java/com/devcourse/ReviewRanger/question/application/QuestionServiceTest.java

- 설문 생성시 만들어지는 질문, 질문 옵션에 대한 기능을 구현했습니다.
- 설문 생성 기능이 큰 작업이다보니 이에 속하는 질문과 질문 옵션 기능을 먼저 구현했습니다.
- api가 설문에 포함되다보니, 이에 따라 추후 수정이 있을 것 같습니다.
- 연관관계를 끊은 상태에서 설문, 질문, 질문 옵션 3단계의 데이터를 받는 과정이 복잡합니다. 
우선 "질문" 엔티티 필드에 디비에 컬럼이 생기지 않도록 options 필드를 생성했습니다. 
여기서 컴마를 통해 옵션값을 구분하고 엔티티 내부에서 questionOptions를 만들어 줍니다.
- 위의 부분은 설문 생성 api가 만들어 질 때 같이 수정될 것 같습니다. 이떄 연관관계도 맺을까 생각중입니다.
해당 부분을 잘 봐주시고 좋은 의견 주시면 좋겠습니다.
- 질문 생성, 질문 옵션 생성에 대해 메서드가 실행되는지를 테스트 했다.

[REV-79] 질문 및 질문 옵션 생성 기능 추가

---

src/main/java/com/devcourse/ReviewRanger/common/config/SecurityConfig.java
src/main/java/com/devcourse/ReviewRanger/common/exception/ErrorCode.java
src/main/java/com/devcourse/ReviewRanger/common/exception/RangerException.java
src/main/java/com/devcourse/ReviewRanger/user/controller/UserController.java
src/main/java/com/devcourse/ReviewRanger/user/domain/User.java
src/main/java/com/devcourse/ReviewRanger/user/dto/JoinRequest.java
src/main/java/com/devcourse/ReviewRanger/user/dto/ValidateEmailRequest.java
src/main/java/com/devcourse/ReviewRanger/user/dto/ValidateNameRequest.java
src/main/java/com/devcourse/ReviewRanger/user/repository/UserRepository.java
src/main/java/com/devcourse/ReviewRanger/user/service/UserService.java
src/test/java/com/devcourse/ReviewRanger/user/service/UserFixture.java
src/test/java/com/devcourse/ReviewRanger/user/service/UserServiceTest.java

- 유저 회원가입, 이름/이메일 검증 추가
- User Fixture Instance를 구현하여 테스트 코드 재사용성 증가
- User Entity의 password에 걸리는 유효성 검증은 암호화된 비밀번호가 들어오는 상황에 적합하지 않다고 판단해 제거 하였습니다.
- 현재 security 권한을 전부 허용하여 api 테스트가 가능하도록 수정하였습니다.
- 유저 회원가입 통합 테스트 진행했습니다. mockito는 시간이 너무 오래걸려서 .. 추후에 추가하도록 하겠습니다

[REV-108] 유저 회원가입, 이름/이메일 검증 추가

---

build.gradle
src/main/java/com/devcourse/ReviewRanger/BaseEntity.java
src/main/java/com/devcourse/ReviewRanger/afterresult/domain/AfterResponse.java
src/main/java/com/devcourse/ReviewRanger/afterresult/domain/AfterResult.java
src/main/java/com/devcourse/ReviewRanger/common/config/SecurityConfig.java
src/main/java/com/devcourse/ReviewRanger/common/config/SwaggerConfig.java
src/main/java/com/devcourse/ReviewRanger/eachSurveyResult/domain/EachSurveyResult.java
src/main/java/com/devcourse/ReviewRanger/question/domain/Question.java
src/main/java/com/devcourse/ReviewRanger/question/domain/QuestionOption.java
src/main/java/com/devcourse/ReviewRanger/response/api/ResponseRestController.java
src/main/java/com/devcourse/ReviewRanger/response/domain/Response.java
src/main/java/com/devcourse/ReviewRanger/survey/domain/Survey.java
src/main/java/com/devcourse/ReviewRanger/surveyresult/domain/SurveyResult.java
src/main/java/com/devcourse/ReviewRanger/user/controller/UserController.java
src/main/java/com/devcourse/ReviewRanger/user/domain/User.java
src/main/java/com/devcourse/ReviewRanger/user/dto/JoinRequest.java
src/main/java/com/devcourse/ReviewRanger/user/dto/ValidateEmailRequest.java
src/main/java/com/devcourse/ReviewRanger/user/dto/ValidateNameRequest.java

- 시큐리티 6.0 이하 버전 사용을 위해 스프링부트를 2.7.17을 사용했습니다.
- 버전변경에 따라 jakarta에서 javax변경작업이 있었습니다.
- 버전변경에 따라 'org.springdoc:springdoc-openapi-starter-webmvc-ui' 가 적용되지 않아 주석처리해두었습니다.
역할이 있던 부분이라 함부로 고치지 않았습니다. 논의 후 제가 변경해도 괜찮을 것 같습니다. 
- 버전변경에 따른 스프링 시큐리 설정파일변경은 "버전변경에 따라 변경된 부분을 전달하기 위한 커밋" 로 빼놓았습니다.

[REV-00] 스프링부트 버전 변경

---

src/main/java/com/devcourse/ReviewRanger/common/exception/ErrorCode.java
src/main/java/com/devcourse/ReviewRanger/common/exception/GlobalExceptionHandler.java
src/main/java/com/devcourse/ReviewRanger/common/exception/RangerException.java
src/main/java/com/devcourse/ReviewRanger/common/response/RangerResponse.java

- Ranger 프로젝트 공통 응답 객체 추가
- ErrorCode에 HttpStatus를 추가함으로서 실패시 클라이언트에게 HttpStatus도 넘기도록 수정
- 앞으로 Controller에 ResponseEntity말고 RangerResponse를 쓰면 될 것 같습니다!!
- 클라이언트에게 반환 할 내용이 더 필요하다면 추후에 추가하도록 하겠습니다.

[REV-139] Ranger 프로젝트 공통 응답 객체 추가

---

src/main/java/com/devcourse/ReviewRanger/survey/dto/response/SurveyResponseDto.java
src/main/java/com/devcourse/ReviewRanger/surveyresult/api/SurveyResultController.java
src/main/java/com/devcourse/ReviewRanger/surveyresult/application/SurveyResultService.java
src/main/java/com/devcourse/ReviewRanger/surveyresult/dto/response/AllResponserResultResponseDto.java
src/main/java/com/devcourse/ReviewRanger/surveyresult/dto/response/Responsers.java
src/main/java/com/devcourse/ReviewRanger/surveyresult/repository/SurveyResultRepository.java

- 작성자별 응답 결과 전체 조회 기능을 구현하였습니다.
- 설문 결과에서 설문 Id가 같으면서 설문에 참여한 컬럼의 갯수를 responserCount로 넣었습니다.
- 설문 단일 조회와 사용자 단일 조회를 충돌을 방지하기 위해 Repository에서 조회에서 사용하였습니다. 추후에 Service의 로직으로 변경할 예정입니다.
- 다음 pr부터 custom RresponseEntitiy 기능을 적용하도록 하겠습니다.
- 다음 pr부터 custom Exception을 적용하도록 하겠습니다.
- 요청자를 식별하기 위해 임시로 pathVariable을 통해 식별값을 받았습니다.
- 테스트코드

[REV-123] 작성자별 응답 결과 전체 조회 기능 구현

---

src/main/java/com/devcourse/ReviewRanger/finalReviewResult/api/FinalReviewResultController.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/application/FinalReviewResultService.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/domain/FinalReviewResult.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/domain/FinalReviewResultReply.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/dto/FinalReviewResultListResponse.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/repository/FinalReviewResultReplyRepository.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/repository/FinalReviewResultRepository.java

- 유저의 마이페이지에서 자신에 대한 리뷰 결과를 전체 조회할 수 있는 기능입니다.
- 응답은 아래와 같이 옵니다.
- 다음으론 최종 리뷰 결과를 생성하는 API 구현 하고 이후 리뷰 결과 상세 조회 기능을 구현하겠습니다!
- DTO에서 Entity를 받아 DTO를 반환하는 로직으로 변환 로직을 구현하였습니다.
- 마이페이지에서 자신의 리뷰 결과를 받아야 하므로 유저 토큰이 필요합니다.

[REV-126] 유저별 리뷰 결과 전체 조회 기능 추가

---

src/main/java/com/devcourse/ReviewRanger/participation/api/ParticipationController.java
src/main/java/com/devcourse/ReviewRanger/participation/application/ParticipationService.java
src/main/java/com/devcourse/ReviewRanger/participation/domain/Participation.java
src/main/java/com/devcourse/ReviewRanger/participation/dto/response/GetParticipationResponse.java
src/main/java/com/devcourse/ReviewRanger/participation/repository/ParticipationRepository.java

- 응답자의 참여 전체조회 기능을 구현했습니다.
- 위의 사진에 필요한 데이터를 추가하다보니, 정답작성여부 필드를 삭제하고, 응답일자 필드를 추가했습니다.
- 정답작성여부 필드 삭제에 따른 기존 참여 서비스 로직을 수정했습니다. 범철님 작성 부분을 수정했어서 반드시 확인 부탁드려요.
- 참여 서비스에서 너무 많은 리포지토리를 의존하고 있습니다. 서비스로 변경하려다보니 서비스 빈간 순환참조 오류가 발생했습니다.
participationService 와 reviewService
- 추후 개선기간에 support 같은 외부 개방 인터페이스를 만들어 수정해야할 것 같습니다.

[REV-164] 응답자의 참여 전체조회 기능 추가

---

src/main/java/com/devcourse/ReviewRanger/participation/api/ParticipationController.java
src/main/java/com/devcourse/ReviewRanger/reply/domain/Reply.java
src/main/java/com/devcourse/ReviewRanger/reply/dto/response/ReplyResponse.java
src/main/java/com/devcourse/ReviewRanger/reviewedTarget/application/ReviewedTargetService.java
src/main/java/com/devcourse/ReviewRanger/reviewedTarget/domain/ReviewedTarget.java
src/main/java/com/devcourse/ReviewRanger/reviewedTarget/dto/response/RepliesByResponserResponse.java
src/main/java/com/devcourse/ReviewRanger/user/application/UserService.java

- 응답자들이 답한 모든 답변을 구해오는 로직입니다.
- 답변과 리뷰 대상의 양방향 관계를 맺었습니다.
- `참여 ID`를 가지고 시작하기 때문에 `참여 컨트롤러`에서 시작하였습니다. 그리고 비지니스 로직을 수행하는 공간은 리뷰 타겟과 답변이기 때문에 리뷰 타겟에서 로직을 수행하였습니다. 혹시 좋은 방향이 있다면 말씀해주시면 감사하겠습니다.
- 로직 설명
- 참여 Id를 통해 리뷰 대상 리스트를 가져온다.
- 리뷰 대상 리스트를 돌면서 리뷰 대상의 Id와 이름을 가져온다.
- 리뷰 대상의 답변들을 돌면서 모든 답변을 가져온다.
- API 테스트를 하는 도중 Json에 무한 루프가 도는 것을 알게되었습니다. 하지만 아무리 디버깅을 찍어봐도 값은 정확해서 우선 올렸습니다.

[REV-124] 응답자의 모든 답변 내용 조회

---

src/main/java/com/devcourse/ReviewRanger/review/api/ReviewController.java
src/main/java/com/devcourse/ReviewRanger/review/application/ReviewService.java
src/main/java/com/devcourse/ReviewRanger/review/dto/response/GetReviewDetailFirstResponse.java

- 프론트 담당자 분과 논의 후 초대 받은 리뷰 첫 조회시 리뷰, 질문, 리뷰 대상 정보 제공 api를 구현했습니다.
- 초대받은 리뷰 조회시 자신을 제외한 피어리뷰 대상자 전체조회 api를 구현했습니다.
- 마감일정을 고려해 화면에 필요한 기능을 위한 api입니다.
- 해당 api를 사용한뒤 점차 분리하는 방향으로 진행해보려합니다.
- 피어리뷰 대상자 전체조회도 추후 분리를 계획해서 같이 구현했습니다.
- 현재는 피어리뷰 대상자중 자신을 걸러서 제공하지만 이 기능도 제외한 전체 조회로 변경할 계획이 있습니다.
- 브랜치명은 다음 pr부터 이슈번호만으로 올리겠습니다.

[REV-170] 초대 받은 리뷰 첫 조회시 리뷰, 질문, 리뷰 대상 정보 제공 api

---

src/main/java/com/devcourse/ReviewRanger/common/exception/ErrorCode.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/api/FinalReviewResultController.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/application/FinalReviewResultService.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/domain/FinalReviewResult.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/repository/FinalReviewResultRepository.java

- 전송 버튼의 전송 기능을 추가했습니다.
- 프론트에게서 받아오는 요청값 없이 테이블에서 리뷰 수신자를 탐색하여 전송합니다.
- 이미 보내진 최종 결과는 제외합니다.
- 트랜잭션이 걸려있어 모두 전송되거나 모두 전송되지 않거나로 작동합니다.
- ErrorCode 부분을 정리했습니다! (404는 모으고 에러 코드를 오름차순으로 정렬)
- controller 스웨거는 최종 리뷰 api를 전부 다 구현하고 (다음 PR이 마지막 구현) 함께 올리겠습니다!

[REV-179] 생성한 최종 리뷰 결과 리뷰대상에게 전송 기능 추가

---

src/main/java/com/devcourse/ReviewRanger/ReplyTarget/application/ReplyTargetService.java
src/main/java/com/devcourse/ReviewRanger/ReplyTarget/domain/ReplyTarget.java
src/main/java/com/devcourse/ReviewRanger/ReplyTarget/dto/request/CreateReplyTargetRequest.java
src/main/java/com/devcourse/ReviewRanger/ReplyTarget/dto/response/ReplyTargetResponse.java
src/main/java/com/devcourse/ReviewRanger/ReplyTarget/repository/ReplyTargetCustomRepository.java
src/main/java/com/devcourse/ReviewRanger/ReplyTarget/repository/ReplyTargetCustomRepositoryImpl.java
src/main/java/com/devcourse/ReviewRanger/ReplyTarget/repository/ReplyTargetRepository.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/application/FinalReviewResultService.java
src/main/java/com/devcourse/ReviewRanger/participation/api/ParticipationController.java
src/main/java/com/devcourse/ReviewRanger/participation/application/ParticipationService.java
src/main/java/com/devcourse/ReviewRanger/review/api/ReviewController.java

- 답변 타겟의 수신자 <-> 유저 `@ManyToOne` 단방향 매핑
- 답변 타겟의 응답자 <-> 유저 `@ManyToOne` 단방향 매핑
- 리뷰를 받은 수신자를 조회하는 기능에서 수신자 이름 검색 기능을 동적 쿼리로 구현하였습니다.
- 디폴트 : 수신자 이름 오름차순
```json
select
replyTarget 
from
ReplyTarget replyTarget   
left join
replyTarget.receiver as replyTarget_receiver 
where
replyTarget.participationId = ?1 
order by
replyTarget_receiver.name asc
```
- searchName=가가 : 이름에 가가가 들어간 이름 찾기 & 수신자 이름 오름차순
```json
select
replyTarget 
from
ReplyTarget replyTarget 
where
replyTarget.participationId = ?1 
and replyTarget.receiver.name like ?2 escape '!' 
order by
replyTarget.receiver.name asc
```
- 유저와의 단방향 매핑을 맺은 이유
- 수신자와 응답자를 반환해야 하는 경우 id뿐만 아니라 이름을 같이 반환해야 하기 때문에 필요하다고 느꼈습니다.
- 답변을 전송할 당시에 프론트에서 수신자와 응답자의 Id 값을 받아오는데 이를 검증해야 하고 이 값을 알맞게 사용할 수 있다고 느꼈습니다.
- 동적 쿼리 구현은 이전 PR와 거의 유사합니다.

[REV-230] 리뷰를 받은 수신자 조회 기능 검색 및 정렬 기능 동적 쿼리 구현

---

build.gradle
src/main/java/com/devcourse/ReviewRanger/ReviewRangerApplication.java
src/main/java/com/devcourse/ReviewRanger/common/config/AsyncConfig.java
src/main/java/com/devcourse/ReviewRanger/participation/repository/ParticipationRepository.java
src/main/java/com/devcourse/ReviewRanger/review/repository/ReviewRepository.java
src/main/java/com/devcourse/ReviewRanger/slack/SlackConstant.java
src/main/java/com/devcourse/ReviewRanger/slack/SlackController.java
src/main/java/com/devcourse/ReviewRanger/slack/SlackService.java

- Slack에 Bot을 생성하여 피어리뷰 마감 기한과 작성하지 않은 사람들을 호출하는 Bot 초안을 구현하였습니다.
- 슬랙봇 서비스가 저희 서버와 동기적으로 진행되는 것을 막기위해 비동기 처리 하였습니다.
- 호출되는 채널을 코드에서 직접 설정해야 하고 사용자를 멘션하기 위해서는 사용자들의 정보를 slack에서 받아와야 합니다. 상대적으로 중요도가 낮아지는 것 같아 후순위로 미루도록 하겠습니다.
- 사용자가 리뷰 식별자를 알 수 없으므로 리뷰 제목을 입력받고 해당 제목을 통해 진행중이면서 가장 최근인 review를 DB에서 가져오도록 하였습니다.

[REV-225] 슬랙봇 서비스 초안 구현

---

build.gradle
src/test/java/com/devcourse/ReviewRanger/question/application/QuestionServiceTest.java
src/test/java/com/devcourse/ReviewRanger/review/api/ReviewControllerTest.java
src/test/java/com/devcourse/ReviewRanger/review/application/ReviewServiceTest.java
src/test/java/com/devcourse/ReviewRanger/user/service/TestPrincipalDetailsService.java

- 리뷰 생성 테스트 코드를 추가했습니다.
- 테스트 환경에서 UserPrincipal 사용을 위해 의존성을 추가하고 testUesrDetailService를 추가했습니다.
- api 테스트는 성공할 때 true값을 주고, 실패는 예외 결과를 반환하기 때문에 성공만 작성헀고 어떤 입력을 받고 반환하는지 표현하기 위해 작성했습니다.
- service 테스트는  도메인 객체에서 유효성 검사를 하다보니 서비스 테스트에서 어떤 경우에 어떤 예외가 발생하는지 표현하기 위해 작성했습니다.
- 요청 dto에서 toEntity로 반환할 때 도메인의 유효성 검사가 일어나기 때문에 서비스 로직에서 테스트가 더 많아졌습니다. 검증 중복이 두번 일어나는게 비효율적이라 생각해서 우선 dto자체에서의 유효성 검사는 보류했습니다. 기능상으론 정상 동작합니다. 우선순위가 높은 것을 끝낸 후 논의하여 맞춰보도록 하겠습니다.
- 어떤 값에 어떤 오류가 발생한다는 것을 바로 전달하기 위해 테스트 메서드 마다 request값을 새로 만들었습니다. 지저분 하다면 다음 관련된 pr을 수행하며 userfixture 형식에 맞춰 작성해보겠습니다.

[REV-216] 리뷰 생성 테스트 코드 추가

---

src/main/java/com/devcourse/ReviewRanger/BaseEntity.java
src/test/java/com/devcourse/ReviewRanger/participation/application/ParticipationServiceTest.java
src/test/java/com/devcourse/ReviewRanger/review/api/ReviewControllerTest.java

- 리뷰에 참여하는 인원 전체 조회 테스트, 리뷰를 받은 인원 전체 조회 테스트를 구현하였습니다.
- 사용자의 Id값이 계속 null이 발생해 setter을 넣어주었습니다.

[REV-246] 수신자별 & 작성자별 전체 조회 테스트 구현

---

src/main/java/com/devcourse/ReviewRanger/common/config/WebConfig.java
src/main/java/com/devcourse/ReviewRanger/common/response/RangerResponse.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/api/FinalReviewResultController.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/application/FinalReviewResultService.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/dto/CheckFinalResultStatus.java

- 모든 수신자가 리뷰 결과를 가지는지 검증 기능 추가 + 리뷰 결과를 갖는 userId 목록을 넘겨주는 기능 추가
https://github.com/prgrms-web-devcourse/Team-12-ReviewRanger-BE/pull/62
- `CheckFinalResultStatus`을 응답으로 받아 무조건 true값이 아닌 boolean 값을 넘겨줄 수 있도록 구현했습니다. 이를 위해 RangerResponse에 함수를 추가했습니다.

[REV-283] 모든 수신자 결과 수신 검증 API 수정

---

src/main/java/com/devcourse/ReviewRanger/finalReviewResult/application/FinalReviewResultService.java
src/main/java/com/devcourse/ReviewRanger/participation/domain/Participation.java
src/main/java/com/devcourse/ReviewRanger/review/domain/Review.java
src/main/java/com/devcourse/ReviewRanger/slack/SlackController.java

- 해당 전송 버튼을 눌렀을 때 최종 리뷰가 전송 상태로 변함과 동시에 리뷰, 참여 Entity도 함께 종료 상태로 변하도록 수정하였습니다.
- 이전 PR -> (#64)
- Entity에서 해당 역할을 수행하도록 하였고 비즈니스 로직에서는 Entity의 메소드만 호출하는 방식으로 구현하였습니다. 도메인!!!

[REV-285] 최종 리뷰 전송 시 리뷰 종료 기능 추가

---

src/test/java/com/devcourse/ReviewRanger/finalReviewResult/domain/ValidateFinalReviewResult.java

- 최종 리뷰 결과 Entity가 repo에 저장될 때 유효성 검사가 잘 일어나는지 테스트하는 테스트 코드를 추가했습니다.
- notValidateFinalReviewResult: 최종 리뷰 결과 필드엔 빈 값이 들어갈 수 없다.
- validateFinalReviewResult: 최종 리뷰 결과 필드에 유효한 필드 값을 넣을 수 있다.

[REV-221] 최종 결과 Entity 유효성 검사 테스트

---

src/main/java/com/devcourse/ReviewRanger/common/config/SecurityConfig.java
src/main/java/com/devcourse/ReviewRanger/common/jwt/ExceptionHandlerFilter.java
src/main/java/com/devcourse/ReviewRanger/common/jwt/JwtFilter.java
src/main/java/com/devcourse/ReviewRanger/common/jwt/JwtTokenProvider.java

- jwt 토큰 유효성 검사에 필요한 jwt 예외 핸들러를 추가적으로 구현하였습니다.
- 유효하지 않은 jwt 응답이 200에서 401으로 변경되었습니다.
- `IllegalArgumentException` 부분 예외 처리는 제외하였는데 postman에서 로그인할 때 토큰을 사용하지 않는데도 토큰 유효성 검사를 하는 문제가 있다고 해서 임시로 처리해 두었습니다! 추후에 주석풀고 테스트 후 배포하면 될 것 같습니다.
- 403은 데이터가 있고 넌 권한이 없음을 암시적으로 전달하기 때문에 보안상 401 응답 코드를 사용했습니다.

[REV-286] jwt 토큰 예외 핸들러 추가

---

src/main/java/com/devcourse/ReviewRanger/ReplyTarget/api/ReplyTargetRestController.java
src/main/java/com/devcourse/ReviewRanger/ReplyTarget/application/ReplyTargetService.java
src/main/java/com/devcourse/ReviewRanger/ReplyTarget/domain/ReplyTarget.java
src/main/java/com/devcourse/ReviewRanger/ReplyTarget/repository/ReplyTargetRepository.java
src/main/java/com/devcourse/ReviewRanger/participation/application/ParticipationService.java
src/test/java/com/devcourse/ReviewRanger/ReplyTarget/api/ReplyTargetRestControllerTest.java
src/test/java/com/devcourse/ReviewRanger/ReplyTarget/application/ReplyTargetServiceTest.java

- ReviewId를 모르고 작성자와 수신자의 Id 값으로 조회하다 보니 모든 리뷰의 작성자 또는 수신자의 응답을 가져왔습니다.
- 그래서 ReviewId를 통해서 특정 리뷰의 작성자 또는 수신자의 응답으로 가져오도록 수정하였습니다.
- 단일 응답 조회의 핵심 로직을 수정하였고, 컨트롤러 및 다른 변경점들은 다음 PR에서 정리해서 올리겠습니다.

[REV-288] 작성자별, 수신자별 응답 조회시 모든 리뷰의 작성자, 수신자를 가져오는 버그 수정

---

src/test/java/com/devcourse/ReviewRanger/finalReviewResult/FinalReviewResultFixture.java
src/test/java/com/devcourse/ReviewRanger/finalReviewResult/application/FinalReviewResultServiceTest.java

- 최종 리뷰 결과 상세조회 비즈니스 로직인 `getFinalReviewResultInfo`, `getFinalReviewAnswerList`에 대한 단위 테스트 코드를 mockito로 작성했습니다.
- 최종 리뷰 도메인 정보 조회와 최종 리뷰에 달린 질문과 답변 리스트 조회에 대한 api가 따로여서 테스트를 따로 진행했습니다!
- 최종_리뷰_결과_상세조회_성공
- 최종_리뷰_결과_상세조회_실패
- 최종_리뷰_결과_답변_상세조회_성공

[REV-224] 최종 리뷰 결과 상세 조회 단위테스트 추가

---

src/test/java/com/devcourse/ReviewRanger/auth/application/AuthServiceTest.java

- 유저 도메인 인증 부문의 로그인 비즈니스 로직 `logout`에 대한 단위 테스트 코드를 mockito로 작성했습니다.
- 로그아웃_성공_테스트

[REV-183] 유저 도메인 로그아웃 단위 테스트 추가

---

src/main/java/com/devcourse/ReviewRanger/finalReviewResult/application/FinalReviewResultService.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/domain/FinalReviewResult.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/domain/FinalReviewResultAnswer.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/domain/FinalReviewResultAnswerDropdown.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/domain/FinalReviewResultAnswerHexStat.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/domain/FinalReviewResultAnswerObjects.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/domain/FinalReviewResultAnswerRating.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/domain/FinalReviewResultAnswerSubject.java
src/test/java/com/devcourse/ReviewRanger/finalReviewResult/application/FinalReviewResultServiceTest.java

- 최종 리뷰 결과 생성시 이미 생성된 데이터가 있음에도 불구하고 중복으로 데이터가 들어가는 것을 방지하는 로직을 추가했습니다
- 최종 결과 답변은 모두에게 공통적으로 보여지는 부분이 아니라 특정 사람에게만 보여지는 항목이라고 생각해 식별을 위한 userId를 추가했습니다.
- 주관식 최종 답변이 update되는 api는 다음 PR에 추가적으로 올리겠습니다!
- 최종_리뷰_중복생성_방지

[REV-319] 최종 리뷰 결과 생성 시 중복 생성 방지 로직 추가

---

src/main/java/com/devcourse/ReviewRanger/common/exception/ErrorCode.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/api/FinalReviewResultController.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/application/FinalReviewResultService.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/domain/FinalReviewResultAnswerSubject.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/dto/UpdateAnswerOfSubject.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/repository/SubjectTypeRepository.java
src/test/java/com/devcourse/ReviewRanger/finalReviewResult/application/FinalReviewResultServiceTest.java

- 최종 결과를 저장할 때 정제된 주관식 응답을 업데이트하는 기능을 추가했습니다.
- 아래 사진에서 저장버튼을 누를 때 동작하는 api입니다.
- 요청은 아래와 같이 옵니다.
```json
{
"userId": 1,
"reviewId": 1,
"questionId": 1,
"answer": "주관식 답변을 정제한 내용입니다. 이것을 다시 저장할게요!!"
}
```
- 누구를 대상으로 한 답변인지 식별이 필요하므로 userId를 통해 답변을 식별합니다.
- 주관식_결과_업데이트_성공: mockito로 `updateAnswerOfSubject`에 대한 단위 테스트를 진행했습니다.

[REV-312] 주관식 답변 결과 업데이트 기능 추가

---

src/main/java/com/devcourse/ReviewRanger/common/exception/ErrorCode.java
src/main/java/com/devcourse/ReviewRanger/common/image/infrastructure/S3manager.java
src/main/java/com/devcourse/ReviewRanger/user/application/UserService.java

- 프로필 이미지의 확장자를 `jpg`, `jpeg`, `png`만 가능하도록 설정하였습니다.
- 프로필 이미지 이름의 중복을 피하기 위해 랜덤 값으로 저장해 두었습니다.

[REV-290] 프로필 이미지 유효성 검증 및 고유한 이름 값 설정

---

src/main/java/com/devcourse/ReviewRanger/finalReviewResult/application/FinalReviewResultService.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/repository/DropdownTypeRepository.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/repository/HexstatTypeRepository.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/repository/ObjectTypeRepository.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/repository/RatingTypeRepository.java
src/main/java/com/devcourse/ReviewRanger/finalReviewResult/repository/SubjectTypeRepository.java
src/test/java/com/devcourse/ReviewRanger/finalReviewResult/application/FinalReviewResultServiceTest.java

- 최종 리뷰 결과의 QNA 내용을 조회하는 로직에 userId를 추가했습니다
- 해당하는 user에 대한 답변을 식별해야 할 필요가 있다고 생각이 들어 추가하게 되었습니다
- 주관식은 한 사람당 한 개만 가지고 있으므로 List가 아닌 단일 객체로 반환받도록 수정하였습니다!!
- 최종_리뷰_결과_답변_상세조회_성공

[REV-322] 최종 리뷰 결과의 QNA 조회 로직 변경

---

src/main/java/com/devcourse/ReviewRanger/common/exception/ErrorCode.java
src/main/java/com/devcourse/ReviewRanger/participation/application/ParticipationService.java
src/test/java/com/devcourse/ReviewRanger/participation/application/ParticipationServiceTest.java
src/test/java/com/devcourse/ReviewRanger/review/application/ReviewServiceSelectTest.java

- 리뷰 마감시 해당 리뷰의 응답자들이 모두 재출했는지 여부 검증로직 추가 
- 테스트 코드 및 api테스트 모두 완료했습니다.
- 리뷰 마감 기능이지만 전체 검증은 참여 서비스에서 발생함으로 참여 서비스에서 검증 로직에 대한 테스트를 진행했습니다.

[REV-298] 리뷰 마감시 리뷰 전체 응답여부 검증 로직 추가

---

src/main/java/com/devcourse/ReviewRanger/ReplyTarget/application/ReplyTargetService.java
src/main/java/com/devcourse/ReviewRanger/ReviewRangerApplication.java
src/main/java/com/devcourse/ReviewRanger/reply/domain/Reply.java
src/main/java/com/devcourse/ReviewRanger/review/api/ReviewController.java
src/test/java/com/devcourse/ReviewRanger/ReplyTarget/api/ReplyTargetRestControllerTest.java
src/test/java/com/devcourse/ReviewRanger/ReplyTarget/application/ReplyTargetServiceTest.java

- 프론트에서 필수가 아닌 질문에 답변에 대한 GET API가 다르게 구현되어 있어 빈 답변 값의 반환 유무에 따라 로직을 분리하였습니다.
- 응답자가 답변을 한 경우 응답자가 자신의 답변을 수정하기 위해 자신의 답변을 GET 요청시
- 필수가 아닌 질문에 답변에 디폴트 값을 넣어서 반환해줍니다.
- 리뷰 생성자가 응답자의 답변을 GET 요청시
- 필수가 아닌 질문에 답변을 포함하지 않고 반환합니다.

[REV-355] 요청에 따라 빈 답변값 반환 유무 분리 로직 구현
