prgrms-web-devcourse/Team-12-ReviewRanger-BE

src/main/java/com/devcourse/ReviewRanger/TestController.java
=> [REV-31] 인프라 테스트용 컨트롤러 구현

.github/workflows/ci.yml
- github action ci test 권한 문제 해결
=> [REV133] ci: gradlew 권한 문제 수정하다

src/main/java/com/devcourse/ReviewRanger/BaseEntity.java
- 공통 필드(id값, 생성날짜, 수정날짜)를 가진 BaseEntity를 추가했습니다
- 각 도메인에 id는 추가하지 않고 BaseEntity를 상속받아 id를 만들면 될 것 같습니다!
=> [REV-130] 공통 필드를 가진 BaseEntity 추가

build.gradle, src/main/java/com/devcourse/ReviewRanger/common/config/SecurityConfig.java, src/main/java/com/devcourse/ReviewRanger/common/jwt/JwtProvider.java
- security, jwt 의존성 추가
- 설정 파일은 초안이므로 무시하셔도 될 것 같습니다!
=> [REV-106] Security 환경 설정하다

src/main/java/com/devcourse/ReviewRanger/BaseEntity.java, src/main/java/com/devcourse/ReviewRanger/ReviewRangerApplication.java, src/main/java/com/devcourse/ReviewRanger/common/regex/UserRegex.java, src/main/java/com/devcourse/ReviewRanger/user/User.java
- BaseEntity 생성, 수정 날짜 변경 감지를 위한 JPA Auditing 기능 활성화
- 유저 Entity (이름, 이메일, 비밀번호) 추가 및 유효성 검사 코드
- 유저 이름은 최소 2글자부터 20자까지 한글 및 대소문자 알파벳, 숫자 그리고 [, ], <, > 특수 문자 허용입니다!!
Ex) [백엔드 4기]장수연, <백엔드 4기>장수연,
- 이메일 형식은 다들 아시다 싶은 그 형식
- 비밀번호 형식은 대소문자 및 숫자로 길이는 최소 8자에서 25자까지 입니다
- 유효성 검사 방법에 대한 리뷰를 위주로 부탁드리곘습니다!
=> [REV-33] 유저 Entity 및 유효성 검사 추가

src/main/java/com/devcourse/ReviewRanger/response/domain/EachSurveyResult.java, src/main/java/com/devcourse/ReviewRanger/response/domain/Response.java
- 응답과 관련된 엔티티를 추가하였습니다.
- 응답의 필드로 객관식과 주관식을 기준으로 작성하였습니다.
=> [REV-41] 응답 관련 엔티티 생성

src/main/java/com/devcourse/ReviewRanger/afterresult/domain/AfterResponse.java, src/main/java/com/devcourse/ReviewRanger/afterresult/domain/AfterResult.java, src/main/java/com/devcourse/ReviewRanger/response/domain/Response.java
- 조합된 결과, 응답에 해당하는 Entity를 추가했습니다
- Getter는 사용할 때만 열어두는게 불변성을 유지하는데에 이로울 것 같아 Entity 초안엔 추가하지 않았습니다.
=> [REV-105] 조합된 결과, 응답 Entity 추가

.github/workflows/deploy.yml
- CI와 CD를 분리하는 과정에서 오타가 발생해 수정했습니다.
=> [REV-53] CI & CD 분리 작업

src/main/java/com/devcourse/ReviewRanger/common/exception/ErrorCode.java, src/main/java/com/devcourse/ReviewRanger/common/exception/GlobalExceptionHandler.java, src/main/java/com/devcourse/ReviewRanger/common/exception/RangerException.java
- 예외 처리를 위한 GlobalHandler 추가
- ErrorCode에 앞으로 추가되는 사용자 정의 예외를 작성해 주시면 될 것 같습니다!
=> [REV-135] 예외 처리를 위한 GlobalHandler 추가

build.gradle, src/main/java/com/devcourse/ReviewRanger/common/config/SwaggerConfig.java
- swagger 초기 세팅을 진행했습니다.
- http://localhost:8080/swagger-ui.html에서 API를 확인할 수 있습니다.
=> [REV-137] 초기 세팅 구현

src/main/java/com/devcourse/ReviewRanger/survey/api/SurveyController.java, src/main/java/com/devcourse/ReviewRanger/survey/application/SurveyService.java, src/main/java/com/devcourse/ReviewRanger/survey/dto/request/CreateSurveyRequest.java, src/main/java/com/devcourse/ReviewRanger/surveyresult/api/SurveyResultController.java, src/main/java/com/devcourse/ReviewRanger/surveyresult/application/SurveyResultService.java, src/main/java/com/devcourse/ReviewRanger/surveyresult/domain/SurveyResult.java, src/main/java/com/devcourse/ReviewRanger/surveyresult/repository/SurveyResultRepository.java
- 요청자 설문 요청시 응답자에게 설문결과가 생성되는 기능을 구현했습니다.
- 응답자가 받은 설문결과 전체조회 기능을 구현했습니다.
- 설문요청 기능에 설문결과 생성 기능을 추가했습니다.
- 토큰값전 응답자 식별은 식별자 값으로 하고 PathVariable로 요청하도록 해두었습니다.
=> [REV- 85] 응답자 초대받은 리뷰 생성 및 조회 구현

src/main/java/com/devcourse/ReviewRanger/survey/api/SurveyController.java, src/main/java/com/devcourse/ReviewRanger/survey/application/SurveyService.java, src/main/java/com/devcourse/ReviewRanger/surveyresult/application/SurveyResultService.java, src/main/java/com/devcourse/ReviewRanger/surveyresult/domain/SurveyResult.java
- 요청자 마감시 설문 및 설문 결과 마감 기능을 구현했습니다.
- api 명시된대로  post를 사용했고, 식별은 pathVariable로 진행했습니다.
=> [REV-87] 설문마감기능 구현

src/main/java/com/devcourse/ReviewRanger/ReviewRangerApplication.java, src/main/java/com/devcourse/ReviewRanger/common/jwt/JwtTokenProvider.java, src/main/java/com/devcourse/ReviewRanger/user/api/UserController.java, src/main/java/com/devcourse/ReviewRanger/user/application/CustomUserDetailsService.java, src/main/java/com/devcourse/ReviewRanger/user/application/UserService.java, src/main/java/com/devcourse/ReviewRanger/user/domain/User.java, src/main/java/com/devcourse/ReviewRanger/user/domain/UserPrincipal.java, src/main/java/com/devcourse/ReviewRanger/user/dto/UpdateRequest.java
- 회원정보 수정 기능을 추가했습니다
- 이름과 비밀번호를 바꿀 수 있는 기능입니다.
- 회원정보 수정 로직은 간단하나 시큐리티가 조금 변했습니다!
=> [REV-111] 회원 정보 수정 기능 추가 + jwt, 시큐리티 설정 변경

src/main/java/com/devcourse/ReviewRanger/common/exception/ErrorCode.java, src/main/java/com/devcourse/ReviewRanger/common/response/RangerResponse.java, src/main/java/com/devcourse/ReviewRanger/eachSurveyResult/repository/EachSurveyResultRepository.java, src/main/java/com/devcourse/ReviewRanger/response/api/ResponseRestController.java, src/main/java/com/devcourse/ReviewRanger/surveyresult/api/SurveyResultController.java, src/main/java/com/devcourse/ReviewRanger/surveyresult/application/SurveyResultService.java, src/main/java/com/devcourse/ReviewRanger/surveyresult/dto/response/AllRecipientParticipateInSurveyDto.java, src/main/java/com/devcourse/ReviewRanger/surveyresult/dto/response/AllResponserParticipateInSurveyDto.java, src/main/java/com/devcourse/ReviewRanger/surveyresult/dto/response/Recipients.java
- 리뷰를 받은 수신자 전체 조회 기능을 구현하였습니다.
- 쿼리문으로 구현하고 싶었지만 구현을 실패하여 Map을 통해 구현하였습니다.
- 비즈니스 로직에서 생각하신 로직이 있으시다면 조언 부탁드립니다.
=> [REV-121] 리뷰를 받은 수신자 전체 조회 기능 구현

build.gradle, src/main/java/com/devcourse/ReviewRanger/common/config/RedisConfig.java, src/main/java/com/devcourse/ReviewRanger/common/config/SecurityConfig.java, src/main/java/com/devcourse/ReviewRanger/common/exception/ErrorCode.java, src/main/java/com/devcourse/ReviewRanger/common/jwt/JwtTokenProvider.java, src/main/java/com/devcourse/ReviewRanger/common/redis/RedisProperties.java, src/main/java/com/devcourse/ReviewRanger/common/redis/RedisUtil.java, src/main/java/com/devcourse/ReviewRanger/user/api/UserController.java, src/main/java/com/devcourse/ReviewRanger/user/application/UserService.java, src/main/resources/application.yml
- redis를 이용한 로그아웃 기능을 구현한 PR입니다
- 기존에 유저 controller에서 유효성 검사가 안 들어간 부분이 있어서 이 부분도 추가했습니다!
- `/logout` path로 진행하고 싶었는데 왜인지 `/login`이랑 자꾸 겹친다고 인식해서 다음에 또 고쳐보곘습니다 ㅠ0ㅠ
=> [REV-112] 유저 로그아웃 기능 추가

src/main/java/com/devcourse/ReviewRanger/user/api/UserController.java, src/main/java/com/devcourse/ReviewRanger/user/application/UserService.java, src/main/java/com/devcourse/ReviewRanger/user/dto/GetUserResponse.java
- 리뷰를 생성할 때 응답자를 지정하기 위해 사용되는 사용자 전체조회 기능입니다.
- responseDto를 봐주시면 GetUserResponse를 만들어 사용되는 데이터만 추가했습니다. 어떻게 생각하시나요?
- 초반 부터 고민이 너무 많았어서 우선 요청시 마다 필요한 dto를 만들고 중복되는 것을 재사용할 계획으로 위와 같이 행동했습니다.
=> [REV-169] 사용자 전체조회 기능 구현

.gitignore, build.gradle, src/main/java/com/devcourse/ReviewRanger/common/config/JasyptConfig.java, src/main/resources/application-jwt.yml, src/main/resources/application.yml
- jwt key를 jasypt로 암호화하며 동시에 gitignore에 추가하였습니다.
- 보안상 jwt key가 올라가면 안 될 것 같아 추가했습니다!
=> [REV-142] secret key jasypt로 암호화

build.gradle
- 스프링부트 2.7버전 query dsl 의존성을 추가했습니다
- 스프링부트 버전을 올리지 않을 것 같아서 2.7 버전으로 진행했습니다!
=> [REV-191] 스프링부트 2.7버전 query dsl 의존성 추가

build.gradle, src/main/java/com/devcourse/ReviewRanger/common/config/SecurityConfig.java, src/main/java/com/devcourse/ReviewRanger/common/config/SwaggerConfig.java, src/main/java/com/devcourse/ReviewRanger/user/api/UserController.java, src/main/java/com/devcourse/ReviewRanger/user/dto/LoginResponse.java, src/main/resources/application.yml, src/test/java/com/devcourse/ReviewRanger/user/service/UserServiceTest.java
- swagger 3.0 적용 + jwt 토큰 적용
- 적용 예시도 올려뒀으니 각자 도메인 컨트롤러에 추가해 주시면 감사하겠습니다
=> [REV-194] swagger 3.0 적용

src/main/java/com/devcourse/ReviewRanger/user/api/UserController.java, src/main/java/com/devcourse/ReviewRanger/user/application/UserService.java, src/main/java/com/devcourse/ReviewRanger/user/domain/User.java, src/main/java/com/devcourse/ReviewRanger/user/dto/UpdateNameRequest.java, src/main/java/com/devcourse/ReviewRanger/user/dto/UpdatePasswordRequest.java
- 이름 변경과 비밀번호 변경이 분리된 각각의 API로 변경되었습니다.
- 추가로 userController에 swagger를 추가했습니다.
=> [REV-195] 이름, 비밀번호 변경 API 분리

src/main/java/com/devcourse/ReviewRanger/question/domain/Question.java, src/main/java/com/devcourse/ReviewRanger/question/domain/QuestionOption.java, src/main/java/com/devcourse/ReviewRanger/question/domain/QuestionType.java, src/main/java/com/devcourse/ReviewRanger/question/dto/request/CreateQuestionOptionRequest.java, src/main/java/com/devcourse/ReviewRanger/question/dto/request/CreateQuestionRequest.java, src/main/java/com/devcourse/ReviewRanger/question/dto/response/GetQuestionOptionResponse.java, src/main/java/com/devcourse/ReviewRanger/question/dto/response/GetQuestionResponse.java, src/main/java/com/devcourse/ReviewRanger/review/api/ReviewController.java, src/main/java/com/devcourse/ReviewRanger/review/dto/request/CreateReviewRequest.java
- 리뷰 생성 기능에 대해 프론트분과 논의된 api 형식에 맞게 수정했습니다.
- 설정해주신 스웨거를 적용했습니다.
-  불필요한 컬럼만 삭제하고 스웨거를 적용했습니다.
=> [REV-166] 리뷰 생성 변경사항 및 스웨거 적용 

src/main/java/com/devcourse/ReviewRanger/participation/api/ParticipationController.java, src/main/java/com/devcourse/ReviewRanger/participation/application/ParticipationService.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/request/SubmitParticipationRequest.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/request/UpdateParticipationRequest.java, src/main/java/com/devcourse/ReviewRanger/reply/application/ReplyService.java, src/main/java/com/devcourse/ReviewRanger/reply/domain/Reply.java, src/main/java/com/devcourse/ReviewRanger/reply/dto/request/CreateReplyRequest.java, src/main/java/com/devcourse/ReviewRanger/reply/dto/request/UpdateReplyRequest.java, src/main/java/com/devcourse/ReviewRanger/reviewedTarget/application/ReviewedTargetService.java, src/main/java/com/devcourse/ReviewRanger/reviewedTarget/dto/request/CreateReviewedTargetRequest.java, src/main/java/com/devcourse/ReviewRanger/reviewedTarget/dto/request/UpdateReviewedTargetRequest.java
-  답변을 수정하는 기능을 구현하였습니다.
- 다수의 답변을 수정해야 하기 때문에 생성과 동일한 구조를 가집니다.
- 오직 답변만 수정 가능하고, 리뷰 대상자와 퀴즈는 변경할 수 없습니다.
=> [REV-128] 답변 수정 기능 구현

src/main/java/com/devcourse/ReviewRanger/participation/application/ParticipationService.java, src/main/java/com/devcourse/ReviewRanger/review/api/ReviewController.java, src/main/java/com/devcourse/ReviewRanger/review/application/ReviewService.java
- 프론트와 협의된 명세에 맞춰 api를 수정하고 스웨거를 적용했습니다.
- 컨벤션으로 사용하는 응답객체 및 예외를 적용했습니다.
=> [REV-168] 리뷰 마감 기능 수정

src/main/java/com/devcourse/ReviewRanger/participation/api/ParticipationController.java, src/main/java/com/devcourse/ReviewRanger/participation/application/ParticipationService.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/request/SubmitParticipationRequest.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/request/UpdateParticipationRequest.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/response/AllResponserParticipateInReviewResponse.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/response/ReceiverResponse.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/response/ResponserResponse.java, src/main/java/com/devcourse/ReviewRanger/reply/dto/request/UpdateReplyRequest.java, src/main/java/com/devcourse/ReviewRanger/reply/dto/response/ReplyResponse.java, src/main/java/com/devcourse/ReviewRanger/review/api/ReviewController.java, src/main/java/com/devcourse/ReviewRanger/review/dto/response/ReviewResponseDto.java, src/main/java/com/devcourse/ReviewRanger/reviewedTarget/application/ReviewedTargetService.java, src/main/java/com/devcourse/ReviewRanger/reviewedTarget/dto/request/CreateReviewedTargetRequest.java, src/main/java/com/devcourse/ReviewRanger/reviewedTarget/dto/request/UpdateReviewedTargetRequest.java, src/main/java/com/devcourse/ReviewRanger/reviewedTarget/dto/response/RepliesByResponserResponse.java
- API 명세에 따른 Path와 네이밍을 수정하였습니다.
- REST API를 자원을 기준으로 작성하다보니 컨트롤러와 서비스가 달랐습니다.
- 리뷰 작성자 전체 조회에서 리뷰 작성일 필드를 submitAt으로 할당했습니다.
=> [REV-158] API 명세에 따른 Path & 네이밍 수정

src/main/java/com/devcourse/ReviewRanger/participation/api/ParticipationController.java, src/main/java/com/devcourse/ReviewRanger/participation/application/ParticipationService.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/response/GetParticipationResponse.java
- 프론트와 논의된 명세에 따라 api를 수정하고 스웨거를 적용했습니다
- 응답값에 참여 식별자만 추가 되었습니다.
=> [REV-165] 응답자의 초대받은 리뷰(참여) 전체조회 기능 수정

src/main/java/com/devcourse/ReviewRanger/participation/api/ParticipationController.java, src/main/java/com/devcourse/ReviewRanger/question/dto/response/GetQuestionOptionResponse.java, src/main/java/com/devcourse/ReviewRanger/question/dto/response/GetQuestionResponse.java, src/main/java/com/devcourse/ReviewRanger/review/api/ReviewController.java, src/main/java/com/devcourse/ReviewRanger/review/application/ReviewService.java, src/main/java/com/devcourse/ReviewRanger/review/dto/response/GetReviewDetailResponse.java, src/main/java/com/devcourse/ReviewRanger/review/dto/response/GetReviewResponse.java
- 리뷰를 상세 조회시 리뷰와 포함된 질문들을 응답하는 기능을 구현했습니다.
- 리뷰 클릭시 포함된 질문 리스트를 불러옵니다. 
- 기존 리뷰 식별자를 통해 질문들을 전체 조회하는 기능을 구현했는데, 프론트와 논의 후 리뷰정보도 필요하단 판단으로 해당 api를 추가 했습니다.
- 스웨거를 적용하며 리뷰 전체 조회도 함께 적용했습니다.
=> [REV-163] 리뷰 상세조회 기능 추가

src/main/java/com/devcourse/ReviewRanger/common/config/WebConfig.java
- cors 전역 설정 적용했습니다.
- 프론트가 요청한 도메인명을 추가했습니다.
- 백앤드도 로컬에서 테스트가 가능하도록 3001포트도 추가했습니다.
- 간단단하게 테스트해서 확인했습니다.
=> [REV-172] cors 전역 설정 적용

src/main/java/com/devcourse/ReviewRanger/participation/api/ParticipationController.java, src/main/java/com/devcourse/ReviewRanger/participation/application/ParticipationService.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/request/SubmitParticipationRequest.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/request/UpdateParticipationRequest.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/response/AllResponserParticipateInReviewResponse.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/response/ReceiverResponse.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/response/ResponserResponse.java, src/main/java/com/devcourse/ReviewRanger/reply/dto/request/CreateReplyRequest.java, src/main/java/com/devcourse/ReviewRanger/reply/dto/request/UpdateReplyRequest.java, src/main/java/com/devcourse/ReviewRanger/reply/dto/response/ReplyResponse.java, src/main/java/com/devcourse/ReviewRanger/review/api/ReviewController.java, src/main/java/com/devcourse/ReviewRanger/review/dto/response/ReviewResponseDto.java, src/main/java/com/devcourse/ReviewRanger/reviewedTarget/application/ReviewedTargetService.java, src/main/java/com/devcourse/ReviewRanger/reviewedTarget/domain/ReviewedTarget.java, src/main/java/com/devcourse/ReviewRanger/reviewedTarget/dto/request/CreateReviewedTargetRequest.java, src/main/java/com/devcourse/ReviewRanger/reviewedTarget/dto/request/UpdateReviewedTargetRequest.java, src/main/java/com/devcourse/ReviewRanger/reviewedTarget/dto/response/RepliesByResponserResponse.java
- 응답 관련 API들에 스웨거를 적용하였습니다.
- Long 타입에서 @NotBlank를 @NotNull로 변경하였습니다.
- @ResponseStatus(CREATED) 를 적용해 201 상태코드를 내렸습니다.
=> [REV-192] 응답 관련 API 스웨거 적용

.github/workflows/ci.yml, appspec.yml, scripts/deploy.sh
- CD 환경 에러로 인해 스크립트 파일을 수정했습니다.
=> [REV-198] codedeploy 스크립트 수정

.github/workflows/ci.yml, .gitignore, src/main/resources/application.yml
- DB설정이 CI를 막는거 같아 따로 파일을 분리하였습니다.
=> [REV-199] CICD 해결을 위한 db관련 yml 분리

src/main/java/com/devcourse/ReviewRanger/participation/application/ParticipationService.java, src/main/java/com/devcourse/ReviewRanger/participation/domain/Participation.java, src/main/java/com/devcourse/ReviewRanger/participation/domain/ReviewStatus.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/response/GetParticipationResponse.java, src/main/java/com/devcourse/ReviewRanger/review/application/ReviewService.java, src/main/java/com/devcourse/ReviewRanger/review/domain/Review.java, src/main/java/com/devcourse/ReviewRanger/review/dto/response/GetReviewDetailFirstResponse.java, src/main/java/com/devcourse/ReviewRanger/review/dto/response/GetReviewDetailResponse.java, src/main/java/com/devcourse/ReviewRanger/review/dto/response/GetReviewResponse.java
- 리뷰상태를 의미하도록 기존 DeadLineStatus를 ReviewsStatus로 변경했습니다.
- 리뷰상태랑 별도로 답변여부를 나타내기 위해 isAnswered 필드를 추가했습니다.
- 리뷰 제출때 상태 변경한 코드를 모두 정답작성 여부로 변경했습니다. 테스트는 다 해봤지만 담당부분 확인 부탁드려요!!
=> [REV-167] 리뷰 상태 네이밍 변경 및 작성 여부 컬럼 추가

src/main/java/com/devcourse/ReviewRanger/common/config/QueryDslConfig.java, src/main/java/com/devcourse/ReviewRanger/finalReviewResult/api/FinalReviewResultController.java, src/main/java/com/devcourse/ReviewRanger/finalReviewResult/application/FinalReviewResultService.java, src/main/java/com/devcourse/ReviewRanger/finalReviewResult/dto/FinalReviewResultListResponse.java, src/main/java/com/devcourse/ReviewRanger/finalReviewResult/dto/PagingFinalReviewRequest.java, src/main/java/com/devcourse/ReviewRanger/finalReviewResult/repository/FinalReviewResultCustomRepository.java, src/main/java/com/devcourse/ReviewRanger/finalReviewResult/repository/FinalReviewResultCustomRepositoryImpl.java, src/main/java/com/devcourse/ReviewRanger/finalReviewResult/repository/FinalReviewResultRepository.java
- 마이페이지 리뷰 결과 리스트를 커서 페이징으로 구현하였습니다. 사이즈는 12입니다.
```
select
finalReviewResult.id,
finalReviewResult.title,
finalReviewResult.createAt as createdAt 
from
FinalReviewResult finalReviewResult 
where
finalReviewResult.userId = ?1 
and finalReviewResult.id > ?2 
and finalReviewResult.status = ?3 
order by
finalReviewResult.id asc 
```
```
select
finalrevie0_.id as col_0_0_,
finalrevie0_.title as col_1_0_,
finalrevie0_.created_at as col_2_0_ 
from
final_review_results finalrevie0_ 
where
finalrevie0_.user_id=? 
and finalrevie0_.id>? 
and finalrevie0_.status=? 
order by
finalrevie0_.id asc limit ?
```
- 수정해야 하는 내용이 분명히 있을 것 같은데 제가 지금 상태가 너무 안 좋아서 초안이라도 올리고 회복 후 진행하도록 하곘습니다 ㅠㅠ 죄송합니다
=> [REV-190] 리뷰 결과 조회 커서 페이징 초안

src/main/java/com/devcourse/ReviewRanger/participation/repository/ParticipationCustomRepository.java, src/main/java/com/devcourse/ReviewRanger/participation/repository/ParticipationCustomRepositoryImpl.java, src/main/java/com/devcourse/ReviewRanger/participation/repository/ParticipationRepository.java, src/test/java/com/devcourse/ReviewRanger/participation/repository/ParticipationCustomRepositoryImplTest.java
- 참여[초대받은 리뷰] 전체 조회 시 커서 페이징 요청을 위한 커스텀 레포지토리를 추가했습니다.
- 페이징을 전체적으로 적용하기에 앞서 확인 받기 위해 pr을 만들었습니다. 레포지토리만 확인 부탁드리겠습니다.
- 파리미터, 네이밍 등을 수연님 것과 맞춰 작성했습니다.
- 테스트 코드를 작성했는데 정말 급하게 동작여부를 확인하기 위해 작성했습니다. 추후 수정할 것 입니다.
=> [REV-241] 참여 전체조회 커서 페이징을 위한 customRepository 추가

src/main/java/com/devcourse/ReviewRanger/participation/api/ParticipationController.java, src/main/java/com/devcourse/ReviewRanger/participation/application/ParticipationService.java, src/main/java/com/devcourse/ReviewRanger/participation/repository/ParticipationCustomRepository.java, src/main/java/com/devcourse/ReviewRanger/participation/repository/ParticipationCustomRepositoryImpl.java, src/main/java/com/devcourse/ReviewRanger/review/api/ReviewController.java, src/main/java/com/devcourse/ReviewRanger/review/application/ReviewService.java, src/main/java/com/devcourse/ReviewRanger/review/repository/ReviewCustomRepository.java, src/main/java/com/devcourse/ReviewRanger/review/repository/ReviewCustomRepositoryImpl.java, src/main/java/com/devcourse/ReviewRanger/review/repository/ReviewRepository.java, src/main/java/com/devcourse/ReviewRanger/user/dto/GetUserResponse.java, src/test/java/com/devcourse/ReviewRanger/participation/repository/ParticipationCustomRepositoryImplTest.java
- 생성자가 만든 리뷰 전체 조회에 대한 커서 페이징을 적용했습니다. 
- 이전 초대 받은 리뷰 전체 조회와 유사합니다.
=> [REV-220] 생성자 리뷰 전체조회 커서 페이징 적용

src/test/java/com/devcourse/ReviewRanger/ReplyTarget/api/ReplyTargetRestControllerTest.java, src/test/java/com/devcourse/ReviewRanger/ReplyTarget/application/ReplyTargetServiceTest.java, src/test/java/com/devcourse/ReviewRanger/ReplyTarget/fixture/ReplyFixture.java, src/test/java/com/devcourse/ReviewRanger/user/service/UserFixture.java
- 작성자별 & 수신자별 답변 조회 기능의 컨트롤러, 서비스 테스트 코드를 구현하였습니다.
- 이전 PR에서 남겨주신 리뷰 추가로 반영하겠습니다.
=> [REV-244] 작성자별 & 수신자별 답변 조회 테스트 구현

src/main/java/com/devcourse/ReviewRanger/common/exception/ErrorCode.java, src/main/java/com/devcourse/ReviewRanger/participation/api/ParticipationController.java, src/main/java/com/devcourse/ReviewRanger/reply/application/ReplyService.java, src/main/java/com/devcourse/ReviewRanger/reply/domain/Reply.java, src/main/java/com/devcourse/ReviewRanger/reply/dto/request/CreateReplyRequest.java, src/main/java/com/devcourse/ReviewRanger/reply/dto/request/UpdateReplyRequest.java, src/test/java/com/devcourse/ReviewRanger/participation/api/ParticipationControllerTest.java, src/test/java/com/devcourse/ReviewRanger/reply/application/ReplyServiceTest.java
- 필수 질문에 대해서 미응답시 검증하는 로직을 구현하였습니다.
- 요청별로 필드를 만들고 아닌 값에 null을 주는 방식의 단점이 점점 나타나는 상황입니다. 서비스 배포 이후, 리팩토링을 진행해보도록 하겠습니다.
=> [REV-245] 필수 질문 미응답 검증 로직 구현

src/main/java/com/devcourse/ReviewRanger/auth/api/AuthController.java, src/main/java/com/devcourse/ReviewRanger/auth/application/AuthService.java, src/main/java/com/devcourse/ReviewRanger/auth/application/CustomUserDetailsService.java, src/main/java/com/devcourse/ReviewRanger/auth/domain/UserPrincipal.java, src/main/java/com/devcourse/ReviewRanger/auth/dto/JoinRequest.java, src/main/java/com/devcourse/ReviewRanger/auth/dto/LoginRequest.java, src/main/java/com/devcourse/ReviewRanger/auth/dto/LoginResponse.java, src/main/java/com/devcourse/ReviewRanger/auth/dto/ValidateEmailRequest.java, src/main/java/com/devcourse/ReviewRanger/auth/dto/ValidateNameRequest.java, src/main/java/com/devcourse/ReviewRanger/common/jwt/JwtTokenProvider.java, src/main/java/com/devcourse/ReviewRanger/finalReviewResult/api/FinalReviewResultController.java, src/main/java/com/devcourse/ReviewRanger/participation/api/ParticipationController.java, src/main/java/com/devcourse/ReviewRanger/review/api/ReviewController.java, src/main/java/com/devcourse/ReviewRanger/user/api/UserController.java, src/main/java/com/devcourse/ReviewRanger/user/application/UserService.java, src/main/java/com/devcourse/ReviewRanger/user/dto/UpdatePasswordRequest.java, src/test/java/com/devcourse/ReviewRanger/user/UserFixture.java, src/test/java/com/devcourse/ReviewRanger/user/service/UserServiceTest.java
- key를 잘못 설정해서 다시 PR 올리겠습니다! 
- https://github.com/prgrms-web-devcourse/Team-12-ReviewRanger-BE/pull/82
=> [REV-212] `user` 도메인과 `auth` 도메인 분리 작업

src/test/java/com/devcourse/ReviewRanger/ReplyTarget/application/ReplyTargetServiceTest.java, src/test/java/com/devcourse/ReviewRanger/participation/api/ParticipationControllerTest.java, src/test/java/com/devcourse/ReviewRanger/participation/application/ParticipationServiceTest.java, src/test/java/com/devcourse/ReviewRanger/reply/application/ReplyServiceTest.java, src/test/java/com/devcourse/ReviewRanger/user/domain/ValidateUser.java, src/test/java/com/devcourse/ReviewRanger/user/service/TestPrincipalDetailsService.java
- 유저 Entity 필드에 걸려있는 유효성을 검증하는 테스트 코드를 추가했습니다.
- USERFIXTURE가 user service 테스트 폴더안에 들어있어서 위치를 수정했습니다!
- validateUser: user 필드에 유효한 필드 값을 넣을 수 있다.
- notValidateUser: user 필드엔 빈 값이 들어갈 수 없다.
=> [REV-182] 유저 Entity 유효성 검사

src/main/java/com/devcourse/ReviewRanger/question/domain/Question.java, src/main/java/com/devcourse/ReviewRanger/question/dto/request/CreateQuestionRequest.java, src/main/java/com/devcourse/ReviewRanger/question/dto/response/GetQuestionResponse.java, src/test/java/com/devcourse/ReviewRanger/participation/api/ParticipationControllerTest.java, src/test/java/com/devcourse/ReviewRanger/question/application/QuestionServiceTest.java, src/test/java/com/devcourse/ReviewRanger/review/ReviewFixture.java, src/test/java/com/devcourse/ReviewRanger/review/application/ReviewServiceSelectTest.java
- 리뷰 전체조회, 상세조회 테스트코드를 추가 했습니다. 
- 질문 객체에  description 필드 추가 요청으로 해당 pr에 함께 추가 했습니다.
- 테스트코드 완벽 합니다.
=> [REV-216] 리뷰 조회 테스트 추가

src/test/java/com/devcourse/ReviewRanger/question/application/QuestionFixture.java, src/test/java/com/devcourse/ReviewRanger/review/api/ReviewControllerTest.java, src/test/java/com/devcourse/ReviewRanger/review/application/ReviewServiceSelectTest.java
- 리뷰 마감 테스트를 추가했습니다.
- 이전 pr에서 누락된 리뷰 조회에 대한 api 테스트를 추가했습니다.
- 테스트를 수행하며 조회, 상태 변경이다보니 로직 검증보단 요청 응답 명세에 초점을 맞춰 진행했습니다.
=> [REV-217] 리뷰 마감 테스트 추가

.github/workflows/deploy.yml, build.gradle, src/main/java/com/devcourse/ReviewRanger/common/config/S3Config.java, src/main/java/com/devcourse/ReviewRanger/common/exception/ErrorCode.java, src/main/java/com/devcourse/ReviewRanger/common/image/infrastructure/ImageManager.java, src/main/java/com/devcourse/ReviewRanger/common/image/infrastructure/S3manager.java, src/main/java/com/devcourse/ReviewRanger/user/api/UserController.java, src/main/java/com/devcourse/ReviewRanger/user/application/UserService.java, src/main/java/com/devcourse/ReviewRanger/user/domain/User.java, src/main/resources/application.yml
- S3에 이미지를 업로드하는 로직을 구현하였습니다.
- 이미지 업로드시 기존 S3 이미지를 삭제하고 다시 업로드 합니다.
- 이미지 업로드시 로컬에 이미지가 저장되어 삭제하는 로직을 넣었습니다.
- S3경로 + 유저Id + 파일 이름으로 Path를 만들었습니다. 경로명은 더 리팩토링하겠습니다.
- 지금 파일 확장자를 검증하지 않는데 다시 리팩토링하겠습니다.
=> [REV-233] 이미지 업로드 기능 추가

src/test/java/com/devcourse/ReviewRanger/participation/api/ParticipationControllerTest.java, src/test/java/com/devcourse/ReviewRanger/participation/application/ParticipationServiceTest.java
- 초대 받은 리뷰 전체조회에 대한 테스트 코드를 추가했습니다.
- 초대 받은 리뷰 마감상태 변경에 대한 테스트 코드를 추가했습니다.
- 짧게 올렸습니다.
=> [REV-219] 초대받은 리뷰(참여) 전체조회 및 마감 테스트 추가

src/test/java/com/devcourse/ReviewRanger/finalReviewResult/application/FinalReviewResultServiceTest.java
- 최종 리뷰 결과 비즈니스 로직인 create에 대한 단위 테스트 코드를 mockito로 작성했습니다.
- 토큰 작업 후 테스트 코드 마저 작성하겠습니다!
- 최종 리뷰 결과 생성 성공 테스트
=> [REV-222] 최종 리뷰 결과 생성 성공 단위 테스트 추가

src/main/java/com/devcourse/ReviewRanger/ReplyTarget/domain/ReplyTarget.java, src/main/java/com/devcourse/ReviewRanger/common/config/SecurityConfig.java, src/main/java/com/devcourse/ReviewRanger/common/jwt/ExceptionHandlerFilter.java, src/main/java/com/devcourse/ReviewRanger/common/jwt/JwtFilter.java, src/main/java/com/devcourse/ReviewRanger/common/jwt/JwtTokenProvider.java, src/main/java/com/devcourse/ReviewRanger/finalReviewResult/domain/FinalReviewResult.java, src/main/java/com/devcourse/ReviewRanger/participation/domain/Participation.java, src/test/java/com/devcourse/ReviewRanger/FinalQuestionFixture.java, src/test/java/com/devcourse/ReviewRanger/ReplyTarget/ReplyTargetFixture.java, src/test/java/com/devcourse/ReviewRanger/finalReviewResult/FinalReviewResultFixture.java, src/test/java/com/devcourse/ReviewRanger/finalReviewResult/application/FinalReviewResultServiceTest.java, src/test/java/com/devcourse/ReviewRanger/participation/ParticipationFixture.java
- 최종 결과 비즈니스 로직인 `sendFinalResultToUsers`에 대한 단위 테스트 코드를 mockito로 작성했습니다.
- 각 Entity, 도메인에 대한 Fixture를 구현하였습니다.
- Fixture를 구현하는 과정에서 메인 코드의 모든 필드값을 받는 생성자를 구현했습니다 (이정도는 문제없다고 체크받았습니다!)
- 최종 리뷰 전송 성공 테스트
=> [REV-235] 최종 리뷰 결과 전송 성공 단위 테스트 추가

src/main/java/com/devcourse/ReviewRanger/ReplyTarget/api/ReplyTargetRestController.java, src/main/java/com/devcourse/ReviewRanger/ReplyTarget/repository/ReplyTargetCustomRepository.java, src/main/java/com/devcourse/ReviewRanger/ReplyTarget/repository/ReplyTargetCustomRepositoryImpl.java, src/main/java/com/devcourse/ReviewRanger/ReviewRangerApplication.java, src/main/java/com/devcourse/ReviewRanger/participation/application/ParticipationService.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/response/ReceiverResponse.java, src/main/java/com/devcourse/ReviewRanger/review/api/ReviewController.java
-  Reply Target에 필드에 reviewId가 들어가 반복문이 아닌 ReviewId로 찾아옵니다. 추가로 groupBy절을 통해 응답자 수를 구합니다.
```
select
replyTarget.receiver.id as receiverId,
replyTarget.receiver.name as receiverName,
count(replyTarget.id) as responserCount 
from
ReplyTarget replyTarget 
where
replyTarget.reviewId = ?1 
group by
replyTarget.receiver.id 
order by
replyTarget.receiver.name asc
```
구현하다보니 이런 구조도 나온 것 같아 공유합니다!
=> [REV-289] 수신자 전체 조회 로직 리팩토링

src/main/java/com/devcourse/ReviewRanger/ReplyTarget/api/ReplyTargetRestController.java, src/main/java/com/devcourse/ReviewRanger/ReplyTarget/application/ReplyTargetService.java, src/main/java/com/devcourse/ReviewRanger/reply/domain/Reply.java
- 질문의 필수 여부가 false이고, 응답을 하지 않은 경우 디폴트 응답값을 통해 값을 저장합니다.
=> [REV-327] 필수가 아닌 질문에 디폴트 응답값 저장 및 조회

src/main/java/com/devcourse/ReviewRanger/common/exception/GlobalExceptionHandler.java, src/main/java/com/devcourse/ReviewRanger/common/jwt/ExceptionHandlerFilter.java
- 예외 처리시에 헤더에 상태 코드를 넣도록 수정하였습니다.
- 최대한 기존 코드를 건드리지 않았습니다.
- 동기적으로 예외 정의랑 GlobalExceptionHandler 외 발생하는 예외를 핸들러로 옮기는 작업이 필요할 것 같습니다.
=> [REV-330] 예외 처리시 헤더에 상태 코드를 넣도록 수정

.gitignore, src/test/java/com/devcourse/ReviewRanger/finalReviewResult/repository/FinalReviewResultPagingTest.java
- SpringBootTest에서 DataJpaTest로 변경했습니다.
- 테스트 환경설정 파일을 gitignore에 추가했습니다.
- 최신순 정렬이므로 앞에 있는 데이터의 id가 가장 큽니다.
- 최종결과_최신순_페이징_성공
=> [REV-332] 최종 리뷰 결과 페이징 테스트 코드 수정

src/main/java/com/devcourse/ReviewRanger/common/exception/ErrorCode.java, src/main/java/com/devcourse/ReviewRanger/participation/application/ParticipationService.java, src/main/java/com/devcourse/ReviewRanger/question/application/QuestionService.java, src/main/java/com/devcourse/ReviewRanger/question/domain/Question.java, src/main/java/com/devcourse/ReviewRanger/review/api/ReviewController.java, src/main/java/com/devcourse/ReviewRanger/review/application/ReviewService.java
- 진행중인 리뷰 삭제 기능을 구현했습니다.
- 리뷰, 질문, 질문옵션, 참여, 답변타겟, 답변을 hard방식으로 삭제합니다.
- 기존 soft delste 방식 및 배포 후 리펙토링 후 추가하기로 논의했었습니다.
- 다만 실제 태스트를 진행하며 없으면 서비스 기본 기능 자체가 없다고 판단이 들어 우선 조취했습니다.
- 또한 리뷰 최종 결과에 대한 영향을 없애기 위해 진행중인 상태에만 삭제 가능하도록 했습니다. 해당 조건은 프론트와 논의해서 반영하겠습니다.
- api 및 기능 테스트만 완료한 상태입니다. 
- 우선적으로 해결해야할 문제가 있어 해당 작업을 완료한 후 테스트 코드를 다시 올리도록 하겠습니다.
=> [Rev-296] 진행중인 리뷰 삭제 기능 구현

src/main/java/com/devcourse/ReviewRanger/common/exception/ErrorCode.java, src/main/java/com/devcourse/ReviewRanger/participation/application/ParticipationService.java, src/main/java/com/devcourse/ReviewRanger/participation/repository/ParticipationRepository.java, src/main/java/com/devcourse/ReviewRanger/review/api/ReviewController.java
- 브라우저에서 임의 조작시 초대받은 리뷰 응답자가 아닌 리뷰결과가 조회회는 오류를 삭제하기 위한 api분리작업을 수행했습니다.
=> [REV-299] 리뷰의 접근하는 사용자의 토큰의 따라 예외 처리 추가 구현

src/main/java/com/devcourse/ReviewRanger/auth/domain/UserPrincipal.java, src/main/java/com/devcourse/ReviewRanger/user/application/UserService.java, src/main/java/com/devcourse/ReviewRanger/user/domain/User.java, src/main/java/com/devcourse/ReviewRanger/user/dto/UserInfoResponse.java
- 유저 정보 조회시 이미지 경로를 반환하도록 추가하였습니다.
=> [REV-359] 유저 정보 조회시 이미지 Path 반환 구현

src/main/java/com/devcourse/ReviewRanger/participation/application/ParticipationService.java, src/main/java/com/devcourse/ReviewRanger/question/application/QuestionService.java
- 리뷰 삭제시 deleteAllInBatch 메서드의  casecade.Delete이 반영되지 않는 문제를 수정했습니다.
- 수정방식은 마감일정이 얼마 남지 않은 상황에서 가장 안전하고 확실하게 자식 테이블을 삭제하고 부모테이블을 삭제하도록 구현했습니다.
- deleteAllInBatch 사용 주의사항에 대한 참고 자료입니다. https://waveofymymind.tistory.com/m/124
- 리펙토링시 범위연산을 지정해서 쿼리 수를 줄이는 방식으로 개선해보겠습니다.
=> [REV-336] 리뷰삭제 오류 수정

src/main/java/com/devcourse/ReviewRanger/ReplyTarget/dto/request/CreateReplyTargetRequest.java, src/main/java/com/devcourse/ReviewRanger/ReplyTarget/dto/request/UpdateReplyTargetRequest.java, src/main/java/com/devcourse/ReviewRanger/auth/domain/UserPrincipal.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/request/SubmitParticipationRequest.java, src/main/java/com/devcourse/ReviewRanger/participation/dto/request/UpdateParticipationRequest.java, src/main/java/com/devcourse/ReviewRanger/reply/domain/Reply.java, src/main/java/com/devcourse/ReviewRanger/reply/dto/request/CreateReplyRequest.java, src/main/java/com/devcourse/ReviewRanger/reply/dto/request/UpdateReplyRequest.java, src/main/java/com/devcourse/ReviewRanger/user/application/UserService.java
- S3에서 이미지의 이름이 한글인 경우 불러오지 못하는 문제가 있어 파일 이름은 UUID값으로만 설정하였습니다.
- 프론트와 답변의 유효성이 달라서 유효성 검사를 추가해주었습니다.
=> [REV-342] 이미지 한글 이름 오류 해결 및 답변 유효성 검사 수정

src/main/java/com/devcourse/ReviewRanger/common/exception/ErrorCode.java, src/main/java/com/devcourse/ReviewRanger/common/exception/GlobalExceptionHandler.java, src/main/java/com/devcourse/ReviewRanger/reply/dto/request/CreateReplyRequest.java, src/main/java/com/devcourse/ReviewRanger/reply/dto/request/UpdateReplyRequest.java, src/main/resources/application.yml
- 유효성 검사에서 0 값을 받지 못하는 오류를 수정하였습니다.
- 이미지의 크기 제한을 풀어주었습니다.
=> [REV-345] 레이팅, 육각 스탯 유효성 검사 수정 및 이미지 크기 제한 설정

build.gradle, src/main/java/com/devcourse/ReviewRanger/common/exception/GlobalExceptionHandler.java, src/main/java/com/devcourse/ReviewRanger/common/image/infrastructure/S3manager.java, src/main/java/com/devcourse/ReviewRanger/common/jwt/ExceptionHandlerFilter.java, src/main/java/com/devcourse/ReviewRanger/common/jwt/JwtTokenProvider.java, src/main/resources/logback.xml
- 테스트시 예외 로깅을 모니터링하기 위해 Cloud Watch를 도입하였습니다.
- 현재 error level의 로깅만 모니터링 하도록 설정하였습니다.
=> [REV-343] AWS Cloud Watch 로깅 추가

src/main/java/com/devcourse/ReviewRanger/user/dto/UserResponse.java, src/test/java/com/devcourse/ReviewRanger/ReplyTarget/api/ReplyTargetRestControllerTest.java, src/test/java/com/devcourse/ReviewRanger/review/api/ReviewControllerTest.java
- 답변 조회시 응답자와 수신자의 반환 객체에 이미지 경로를 추가해주었습니다.
- 테스트에서 받은 피드백입니다!
=> [REV-391] 답변 조회시 응답자 & 수신자 반환 객체에 이미지 경로 추가

.github/workflows/deploy.yml, Dockerfile, appspec.yml, build.gradle, scripts/deploy.sh, src/test/java/com/devcourse/ReviewRanger/user/UserFixture.java
- 도커를 도입하여 프로젝트를 빌드하도록 구현하였습니다.
- 도커를 도입한 이유
- 지속적인 개발을 위해 독립적인 공간에서 환경을 통일할 수 있습니다.
- 추후 스케일 아웃을 대비해 도입하였습니다.
=> [REV-407]  Docker 도입

src/main/java/com/devcourse/ReviewRanger/common/config/SwaggerConfig.java, src/main/java/com/devcourse/ReviewRanger/common/config/Workaround.java
- Certbot를 활용해 https를 적용하였습니다.
- Let's Encrypt를 통해 SSL 인증서를 발급받았습니다.
- swagger에서 http와 https를 둘다 확인할 수 있도록 확장하였습니다.
=> [REV-409] swagger release 서버 추가 구현
